[package]
name = "gz-vs-zstd"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"
zstd = "0.13"
rand = "0.8"
indicatif = "0.17"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
